[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

; PHP-FPM
[program:php-fpm]
process_name=%(program_name)s_%(process_num)02d
command=/usr/local/sbin/php-fpm -F
autostart=true
autorestart=true
numprocs=1
stdout_logfile=/var/log/supervisor/php-fpm.log
stderr_logfile=/var/log/supervisor/php-fpm.log

; Nginx
[program:nginx]
process_name=%(program_name)s_%(process_num)02d
command=/usr/sbin/nginx -g 'daemon off;'
autostart=true
autorestart=true
numprocs=1
stdout_logfile=/var/log/supervisor/nginx.log
stderr_logfile=/var/log/supervisor/nginx.log

[program:laravel-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/html/artisan queue:work --queue=default --tries=3 --timeout=90
autostart=true
autorestart=true
numprocs=1
redirect_stderr=true
stdout_logfile=/var/log/supervisor/worker.log
